name: CI
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpunit:
    name: PHPUnit (PHP ${{ matrix.php-version }} on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, windows-latest]
        php-version: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: curl, mbstring, openssl, xml
          coverage: none

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: composer install --ansi --prefer-dist --no-interaction --no-progress

      - name: PHPUnit Migrate Configuration
        if: ${{ matrix.php-version >= '8.0' }}
        run: vendor/bin/phpunit --migrate-configuration

      - name: Run Unit Tests (PHP 5.6)
        if: ${{ matrix.php-version == '5.6' }}
        run: vendor/bin/phpunit --configuration phpunit-5.6.xml --testsuite UnitTest

      - name: Run Unit Tests (PHP 7.0+)
        if: ${{ matrix.php-version != '5.6' }}
        run: vendor/bin/phpunit --testsuite UnitTest
